### PR TITLE
Th extra

### PR DESCRIPTION
**Pull request by TimothyHarley**
- Added a header to the Merchandise page
- Added some more buy button styling
- Added picture borders 
- Added buy button functionality 
- Cleaned up the code a little

### CODE REVIEW

**Comment by MCrank** [comment]
Sweet. Burning the midnight Oil?  🌙 🦉. I'll pull it down in a sec

________________________________

**Comment by MCrank** [comment]
👍 Love it!

**Comment by rrice1** [comment]
Marco's tour schedule page looks like it doesnt have its most recent updates? Not sure why

**Comment by MCrank** [comment]
I merged it into master. Did you pull master down?

________________________________

**Comment by TimothyHarley** [comment]
I've got it up to date with the latest master

**Comment by ChaseHamby** [comment]
👍

**Pull request merged**
