### PR TITLE
Rr navbartop

### PR DESCRIPTION
**Pull request by rrice1**
related to #53

### CODE REVIEW

**Comment by MCrank** [comment]
@rrice1 Looks like the NavBar width is just a few pixels too wide or something.  Gives us a scroll bar at the bottom on your branch but master with the old NavBar does not.

**Comment by MCrank** [comment]
@rrice1 Found the issue.  Get rid of the `margin-right: -8px;` on the `body` element in the CSS.  The bar is still full length but that value is causing the scroll bar at the bottom.

**Comment by rrice1** [comment]
just removed it. thanks for finding that!

**Comment by ChaseHamby** [comment]
👍

**Pull request merged**
